### ISSUE TITLE
Project Research Plan

### ISSUE THREAD

**Issue by dapoadedire** [zuri-training/my-cms-pjt-13#14]

**Comment by 010220010** [comment]
Research hypothesis -[  ]
(https://docs.google.com/document/d/1Cee-S3lUKkyHGsjpUx_jx9G2Vai0wcyO/edit?usp=drivesdk&ouid=110299060158816462160&rtpof=true&sd=true)

Interview appeal - https://docs.google.com/document/d/1CSUIYOxnpVxtb4crGGFBo1HkLqQYNNQY/edit?usp=drivesdk&ouid=110299060158816462160&rtpof=true&sd=true

Research plan - https://docs.google.com/document/d/1BYBcrRRfNrpNzCFC7VsOOZge3EwNJNVy/edit?usp=drivesdk&ouid=110299060158816462160&rtpof=true&sd=true
